
export const preloadHandlebarsTemplates = async function() {

  // Define template paths to load
  const templatePaths = [

	  // Actor Sheet Partials
	  "systems/city-of-mist-ii/templates/parts/theme-display.html",
	  "systems/city-of-mist-ii/templates/parts/tag-display.html",
	  "systems/city-of-mist-ii/templates/parts/improvement-display.html",
	  "systems/city-of-mist-ii/templates/parts/move-display.html",
	  "systems/city-of-mist-ii/templates/parts/status-display.html",
	  "systems/city-of-mist-ii/templates/parts/clue-display.html",
	  "systems/city-of-mist-ii/templates/parts/juice-display.html",
	  "systems/city-of-mist-ii/templates/parts/gmmove-display.html",
	  "systems/city-of-mist-ii/templates/parts/story-tag-display.html",
	  "systems/city-of-mist-ii/templates/parts/story-tag-list-display.html",
	  "systems/city-of-mist-ii/templates/parts/story-tag-header.html",
	  "systems/city-of-mist-ii/templates/parts/tag-name.html",
	  "systems/city-of-mist-ii/templates/parts/gmmoves-section.hbs",
	  "systems/city-of-mist-ii/templates/parts/bio-display.html",
	  "systems/city-of-mist-ii/templates/parts/spectrum-display.html",
	  "systems/city-of-mist-ii/templates/parts/status-text-list.html",
	  "systems/city-of-mist-ii/templates/parts/character-sheet-header.html",
	  "systems/city-of-mist-ii/templates/parts/threat-sheet-header.html",
	  "systems/city-of-mist-ii/templates/parts/lock-button.html",
	  "systems/city-of-mist-ii/templates/parts/danger-template.html",
	  "systems/city-of-mist-ii/templates/parts/clue-journal-display.html",
	  "systems/city-of-mist-ii/templates/parts/gmmove-part.hbs",
	  "systems/city-of-mist-ii/templates/parts/themebook-questions.hbs",
	  "systems/city-of-mist-ii/templates/parts/tag-list-display.hbs",
	  "systems/city-of-mist-ii/templates/chatmessages/downtime-part.hbs",
	  "systems/city-of-mist-ii/templates/parts/status-name.hbs",
	  "systems/city-of-mist-ii/templates/parts/tag-or-status-name.hbs",
	  "systems/city-of-mist-ii/templates/parts/status-with-controls.hbs",
	  "systems/city-of-mist-ii/templates/dialogs/roll-modifier.hbs",
	  "systems/city-of-mist-ii/templates/parts/tag-or-status.hbs",
	  "systems/city-of-mist-ii/templates/parts/tag-or-status.hbs",
	  "systems/city-of-mist-ii/templates/parts/city-roll-modifier.hbs",
	  "systems/city-of-mist-ii/templates/parts/themekit-questions.hbs",
	  "systems/city-of-mist-ii/templates/parts/themekit-improvements.hbs",
	  "systems/city-of-mist-ii/templates/parts/loadout-theme.hbs",
	  "systems/city-of-mist-ii/templates/parts/theme-display-com-front.hbs",
	  "systems/city-of-mist-ii/templates/parts/theme-display-com-back.hbs",
	  "systems/city-of-mist-ii/templates/parts/theme-display-me-front.hbs",
	  "systems/city-of-mist-ii/templates/parts/theme-display-me-back.hbs",
	  "systems/city-of-mist-ii/templates/parts/loadout-theme-back.hbs",
	  "systems/city-of-mist-ii/templates/parts/loadout-theme-front.hbs",
	  "systems/city-of-mist-ii/templates/parts/juice-clues-card.hbs",
	  "systems/city-of-mist-ii/templates/parts/status-story-tag-card.hbs",
	  "systems/city-of-mist-ii/templates/parts/juice-list.hbs",
	  "systems/city-of-mist-ii/templates/parts/clue-list.hbs",
	  "systems/city-of-mist-ii/templates/parts/tag-status-card.hbs",
	  "systems/city-of-mist-ii/templates/parts/build-up-section.hbs",
	  "systems/city-of-mist-ii/templates/parts/move-create-tag-com.hbs",
	  "systems/city-of-mist-ii/templates/parts/move-create-tag-me.hbs",
	  "systems/city-of-mist-ii/templates/parts/relationship-tags-list-display.hbs",
	  "systems/city-of-mist-ii/templates/parts/systemComp.hbs",
	  "systems/city-of-mist-ii/templates/parts/systemComp.hbs",
	  "systems/city-of-mist-ii/templates/parts/themePointControls.hbs",
  ];

  // Load the template parts
  return loadTemplates(templatePaths);
};
